name = "scholarship-api"
main = "src/worker.jsx"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# SUPABASE_URL=http://localhost:54321
# SUPABASE_SERVICE_ROLE_KEY=sb_secret_....
# TURNSTILE_SECRET_KEY=0x4....
# TURNSTILE_UPLOAD_SECRET_KEY=0x4....

[observability]
enabled = true
